name: allure-report

on:
  workflow_dispatch:
    inputs:
        logLevel:
           description: 'Log level'     
           required: true
           default: 'warning'
        tags:
           description: 'Test scenario tags'
  release:
    types:
      - created
  push:
    branches-ignore:
      - '!master'

jobs:
  allure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install --with-deps
    - run: npm run test

    - uses: actions/upload-artifact@master
      with:
        name: my-allure-results
        path: my-allure-results
        retention-days: 20
        
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: my-allure-results
        #gh_pages: gh-pages
        allure_report: generated-allure-report
        #allure_history: allure-history
        #keep_reports: 20

    - name: copy customTab
      env:
          SRC_FOLDER_PATH: 'custom'
          TARGET_BRANCH: 'gh-pages'
          ORIGIN_BRANCH: 'main'
          RUN: ${{github.run_number}}
      run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git switch ${TARGET_BRANCH}
          git checkout ${ORIGIN_BRANCH} -- $files # copy files from the source branch
          ls -al
          sudo cp -Rf custom/* allure-history/${RUN}
          ls -al allure-history/${RUN}
          # git add allure-history
          # git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          # git push origin $TARGET_BRANCH # push to remote branch
          
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
