name: allure-report

on:
  workflow_dispatch:
    inputs:
        logLevel:
           description: 'Log level'     
           required: true
           default: 'warning'
        tags:
           description: 'Test scenario tags'
  release:
    types:
      - created
  push:
    branches-ignore:
      - '!master'

jobs:
  allure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install --with-deps
    - run: npm run test

    - uses: actions/upload-artifact@master
      with:
        name: my-allure-results
        path: my-allure-results
        retention-days: 20
        
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: my-allure-results
        #gh_pages: gh-pages
        allure_report: generated-allure-report
        #allure_history: allure-history
        #keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
